### ISSUE TITLE
Deployment fails on clusters with containerd when credentials are empty

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/fissile#487]
This line does not work when we don't need credentials for Docker hub
https://github.com/cloudfoundry-incubator/fissile/blob/c617cf6372fe75ebe255f2920c1dff6d6d0059ba/kube/registry_credentials.go#L23
Deployment fails. See more in slack thread https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1551369471021700

**Comment by alex-slynko** [comment]
cc @cloudfoundry-incubator/eirini

**Comment by gdankov** [comment]
Any news on this?

**Comment by jandubois** [comment]
@gdankov: I've created a PR so that `imagePullSecrets` aren't generated when the username is empty:

```
      {{- if ne .Values.kube.registry.username "" }}
      imagePullSecrets:
      - name: "registry-credentials"
      {{- end }}
```

The same condition is also put around the whole contents of `registry-secret.yaml`.

You can can point the SCF build to the `checks/fissile-7.0.0+297.g2485f273.linux-amd64.tgz` CI build by changing the fissile flavour and version at https://github.com/SUSE/scf/blob/develop/bin/common/versions.sh#L12-L13.

Please let us know if this fixes the problem for you!

**Comment by jandubois** [comment]
@gdankov @alex-slynko 

> Please let us know if this fixes the problem for you!

There merging of this PR is currently blocked on getting confirmation that the change fixes the issue; so please report back as soon as you know!

**Comment by jandubois** [comment]
@gdankov @alex-slynko 

Any news on this?

**Comment by akshaymankar** [comment]
Hey @jandubois, I am from the eirini team and am working on the story now. I am happy to report that the PR is working as expected. Thanks for the fix!
